# Generated by Django 5.2.8 on 2026-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
