# Generated by Django 5.2.8 on 2026-01-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_features_product_purpose_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, verbose_name='Назначение'),
        ),
    ]
